### ISSUE TITLE
QA: update IG name (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-epr-ppqm#12]
<html>
<body>

ImplementationGuide | warning | ig-0: 'Name should be usable as an identifier for the module by machine processing applications such as code generation' Rule 'Name should be usable as an identifier for the module by machine processing applications such as code generation' Failed
-- | -- | --

</body>
</html>

`name: CH_EPR_PPQm` this would be according to the rule.

**Comment by unixoid** [comment]
Done.  Just wonder why the original value "ch_epr_ppqm" was not usable as an identifier.
