### ISSUE TITLE
Missing menupoints for Profile and Terminology (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-ppqm#14]
ch.fhir.ig.ch-epr-ppqm#0.2.0 /

The IG has only menu Home/Artifacts but there are also Profiles, CodeSystems and ValueSets defined in the IG.
Normally there are Menu Entries for that to finde faster the profiles or codes.

Roeland Luykx (RALY GmbH)

**Comment by unixoid** [comment]
Duplicate of #8.
