### ISSUE TITLE
include HTML fragments

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-epr-ppqm#15]
New requirements for IG (through update HL7 IG publisher):

<html>
<body>

1 | warning | The HTML fragment 'ip-statements.xhtml' is not included anywhere in the produced implementation guide
-- | -- | --
2 | warning | The HTML fragment 'cross-version-analysis.xhtml' is not included anywhere in the produced implementation guide
3 | warning | The HTML fragment 'dependency-table.xhtml' is not included anywhere in the produced implementation guide
4 | warning | The HTML fragment 'globals-table.xhtml' is not included anywhere in the produced implementation guide

</body>
</html>

How to do it, see here: https://github.com/hl7ch/ch-core/commit/6d10475f015024d6b6bb68dfa96e614d82e37630

**Comment by unixoid** [comment]
Thank you, is fixed.
