### ISSUE TITLE
PpqmConsent: use valid examples

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-ppqm#19]
In PpqmConsent, use example URNs instead of 'Local eCMS identifier' in general examples.

**Comment by unixoid** [comment]
Could you please elaborate on what you mean?  Which eCMS?

**Comment by qligier** [comment]
Sure, in http://fhir.ch/ig/ch-epr-ppqm/StructureDefinition-PpqmConsent.html: 
![image](https://github.com/ehealthsuisse/ch-epr-ppqm/assets/3299399/a455581e-927e-4280-9728-809df38ccd51)

**Comment by dkotlaris** [comment]
26.10.2023: Accepted.

**Comment by unixoid** [comment]
@qligier: The requested change seems impossible.  With SUSHI/FSH, you can add examples, but not override existing ones.  Even the direct indexing like described in https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/How.20to.20Profile.20Consent.20When.20You.20Must.20Support.20R4 does not work.

**Comment by unixoid** [comment]
Won't fix.  In FHIR R5 this inappropriate example is gone, no need to invest efforts now.
