### ISSUE TITLE
Describe transactions in a proper page

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-ppqm#20]
Describe transactions in a full page, as it's done in CH-mHealth.
Although their diagrams are quite detailed, the transactions could be better described in a full page.

**Comment by unixoid** [comment]
Transactions are described in an Amendment of Annex 5 EPRO-FDHA (currently a draft), i.e. the situation is exactly the same as for CH:ATC -- the definitions are split.

**Comment by qligier** [comment]
Amendment 2.4?
Is there a requirement to only put the transactions in the amendment? Splitting the transactions and resource profiles is not particularly good for documentation, and also weird because they are tied. CH EPR mHealth is much better in this regard.

**Comment by unixoid** [comment]
Yes, probably it will be 2.4.  And yes, unfortunately it is not alowed to have only the FHIR IG -- I discussed this with eHealth Suisse multiple times.  Again, same as with CH:ATC.  And I suppose, when CH EPR mHealth will be going normative, the same problem will arise.

**Comment by qligier** [comment]
Okay, that is quite disappointing. Closing then!
