### ISSUE TITLE
PPQm Policy Set Template ID issues

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-ppqm#21]
Can we link to https://github.com/ehealthsuisse/ch-epr-adr-ppq/tree/main/Privacy%20Policy%20Stack/Patient%20Specific%20via%20Policy%20Manager from the value set page for reference?

The templates are not described anywhere, their use is quite confusing at first. A link to the description in Annex 5, 2.1 could be enough.

Why are numbers used instead of their actual identifier? E.g. 201 is actually `urn:uuid:e693657c-50be-46a6-bdcd-05269147f357`, and is referenced as such in XACML.

**Comment by unixoid** [comment]
`urn:uuid:e693657c-50be-46a6-bdcd-05269147f357` is a sample identifier of the policy set, its counterpart in the PPQm example is `urn:uuid:57ab9b0d-7d97-4d85-9e4b-02bc7c939ad9`.  `201` is a template ID and present only in FHIR resources, not in XACML.

**Comment by qligier** [comment]
Hmm okay, they are not the same template instances. But then I have troubles understanding the use of templates. They seem to be more than simple examples because you can link them in Consent, but they are not true policies like Base Policies/Base Policy Sets.

**Comment by unixoid** [comment]
Templates are not examples, they are literally templates, i.e. to be filled with actual data.  Please see Section 4.2 in Amendment 2.1 of Annex 5:

> The CH:PPQ Policy Source SHALL create Patient Policies from the template policies by setting 
actual data (e.g. EPR-SPIDs of patients or references to Base Policy Sets) and generate policy set 
IDs as UUIDs. 

See also: 
- [EPR Policy Set templates in Apache Velocity format](https://github.com/oehf/ipf/tree/master/commons/ihe/xacml20/impl/src/main/resources/templates)
- [MAG PPQm issue](https://github.com/i4mi/MobileAccessGateway/issues/81).

**Comment by dkotlaris** [comment]
26.10.2023: Accepted.
