### ISSUE TITLE
Missing referenced Policy Sets

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-ppqm#22]
In PPQm Referenced Policy Set, two Policy Sets are missing: `urn:e-health-suisse:2015:policies:policy-bootstrap` and `urn:e-health-suisse:2015:policies:doc-admin`.
Are they forbidden here, or were they forgotten ?
If forbidden, a short explanation would be useful.

**Comment by unixoid** [comment]
Nothing is forgotten :-)
These policy sets are never referenced from templates, see Section 2 in https://github.com/ehealthsuisse/ch-epr-adr-ppq/blob/main/docs/Policies.md.

**Comment by qligier** [comment]
Is it only in the schema, where policy sets 1-9 are shown? In 2.2, they are described like the 9 others.

**Comment by unixoid** [comment]
The picture https://github.com/ehealthsuisse/ch-epr-adr-ppq/raw/main/docs/policies.png shows, which base policy sets (on the magenta background) may be referenced from policy set templates (on the yellow background).  As you see, `doc-admin` and `policy-bootstrap` are not among them.  As the CH:PPQm profile covers only policy sets created from the templates, it completely ignores the existence of `doc-admin` and `policy-bootstrap`.

If, at some point, the coding system `PpqmReferencedPolicySet` will lose the prefix `Ppqm` in its name and be moved from the CH:PPQm IG to the CH:EPR-Term IG, then yes, it will have to include all references.  But not yet.

**Comment by qligier** [comment]
> If, at some point, the coding system PpqmReferencedPolicySet will lose the prefix Ppqm in its name and be moved from the CH:PPQm IG to the CH:EPR-Term IG, then yes, it will have to include all references. But not yet.

In that case, you would still need a _PpqmReferencedPolicySet_ value set. It makes sense not to have the two special elements here, I only wish a note explaining the value set does not contain the admin policy sets because they are not actionable, and thus forbidden in these exchanges.

**Comment by unixoid** [comment]
Ok, I will add such comment.

**Comment by unixoid** [comment]
And, BTW, I will not still need this value set.  Actually, neither do I need it now.  This is because of the `ch-epr-ppqm-template-structure` validation constraint in PpqmConsent.

**Comment by qligier** [comment]
It is also used as binding on Consent.policyRule.coding.

(Typo in ch-epr-ppqm-template-structure: correspong -> correspond)

**Comment by unixoid** [comment]
This is what I mean, this binding is not necessary as its effect is duplicated in the validation constraint.  But I will keep it nevertheless.

(Thanks.)

**Comment by qligier** [comment]
Okay, I understand now, thanks!

**Comment by unixoid** [comment]
Can this ticket be closed then?

**Comment by unixoid** [comment]
Nvm, a comment and a typo are due...

**Comment by dkotlaris** [comment]
26.10.2023: Accepted.
