### ISSUE TITLE
Change resource profile names

### ISSUE THREAD

**Issue by unixoid** [ehealthsuisse/ch-epr-ppqm#23]
Resource profile names `PpqmRequestBundle` and `PpqmResponseBundle` are unhappy because they look as being request and response messages of the same transaction.  In reality, `PpqmRequestBundle` is used in PPQ-4, and `PpqmResponseBundle` in PPQ-5.  Therefore, they should be renamed e.g. to `PpqmFeedRequestBundle` and `PpqmSearchResponseBundle`.

UPD: `PpqmRetrieveResponseBundle` instead of `PpqmSearchResponseBundle`.

**Comment by qligier** [comment]
In the index, PPQ-5 is called "Mobile Privacy Policy Retrieve", not Search, it could be confusing.

I would associate "retrieve" with getting a single resource, so renaming PPQ-5 "Mobile Privacy Policy Search" seems a good solution I think.

**Comment by unixoid** [comment]
For me, the semantical difference between "search" and "retrieve" is that 
- "search" may deliver only references (IDs, names) of the found objects instead of their actual contents -- e.g. like ITI-18 with the result type "ObjectRef".
- "retrieve" does not imply the necessity of searching -- e.g. when the client already knows a policy set ID and specifies it in a PPQ-2 or PPQ-5 request.

In that way, PPQ-5 is for me clearly of the type "retrieve".

**Comment by qligier** [comment]
In FHIR, search and retrieve are a bit less distinct, because you retrieve when you search.
But retrieve is fine, I would suggest using `PpqmRetrieveResponseBundle` for consistency.

**Comment by unixoid** [comment]
You are right, thanks.

**Comment by dkotlaris** [comment]
26.10.2023: Accepted.
