### ISSUE TITLE
Home: Meaning of MustSupport (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-ppqm#25]
ch.fhir.ig.ch-epr-ppqm#2.0.0-ballot /

In the IG the flag MustSupport is used, but the meaning is nowhere described.

Michaela Ziegler, ahdis ag

**Comment by unixoid** [comment]
@ziegm : I think I will simply delete all MustSupport flags -- Ok for you?

**Comment by ziegm** [comment]
If there is no special use for it, then I think that would be a good way.

**Comment by unixoid** [comment]
https://github.com/hl7ch/ch-core/wiki/Guidelines-for-Swiss-IG-Development#2-use-of-must-support

**Comment by dkotlaris** [comment]
26.10.2023: Accepted
