### ISSUE TITLE
PpqmRequestBundle Response? (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-ppqm#26]
ch.fhir.ig.ch-epr-ppqm#2.0.0-ballot /StructureDefinition-PpqmRequestBundle.html

What should the response be on this transaction? Any example?

Roeland Luykx (RALY GmbH)

**Comment by dkotlaris** [comment]
26.10.2023: Accepted.
