### ISSUE TITLE
Mobile Privacy Policy Bundle Feed (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-ppqm#27]
ch.fhir.ig.ch-epr-ppqm#2.0.0-ballot /

in the sequence diagram is written "transaction-outcome" as type of the response.
there is no such type defined in http://hl7.org/fhir/R4/valueset-bundle-type.html
on a bundle request of type transaction a transaction-response should be sent back.
Missing examples.

Roeland Luykx (RALY GmbH)

**Comment by dkotlaris** [comment]
26.10.2023: Accepted.
