### ISSUE TITLE
enable ci-build of ig

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-ppqm#3]
can the ci-build of the ig be activated that the ig is built with each change?

see equivalenc in ch-epr-mhealth https://github.com/ehealthsuisse/ch-epr-mhealth/settings which when the webhook is excecuted the ci build result will be available at https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/

can help with the setup if needed

**Comment by unixoid** [comment]
Done.  Published on http://build.fhir.org/ig/ehealthsuisse/ch-epr-ppqm/branches/master/index.html.
