### ISSUE TITLE
Separate tabs (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-epr-ppqm#8]
For easier navigation in the IG, separate tabs for "Profiles" and "Terminology" would be helpful, analogous to the other Swiss IGs.

**Comment by unixoid** [comment]
Any idea how to let SUSHI automatically generate separate HTML (XHTML, Markdown, whatever) pages for profiles, terminologies, examples, etc.?  

As of now, I use anchors of artifacts.html, but this does not look good.

**Comment by ziegm** [comment]
Does this structure help?
https://github.com/ahdis/ch-ig/tree/master/input/pagecontent
https://github.com/ahdis/ch-ig/blob/master/sushi-config.yaml#L32

**Comment by unixoid** [comment]
@ziegm Yes it does -- thank you!
